Updates in some cities and states from Colombia
dr5hn/countries-states-cities-database pull request #372
Opened 2022-01-22 16:09 UTC by cesariverit

2022-01-28 06:32 UTC, dr5hn commented on sql/world.sql
> +(2900, 'Archipiélago de San Andrés, Providencia y Santa Catalina', 48, 'CO', '25', 'SAP', NULL, 12.55673240, -81.71852530, '2019-10-05 23:18:51', '2021-07-17 16:39:32', 1, 'Q26855'),
@cesariverit This addition makes a name quite long. Is this really needed?

2022-01-28 06:33 UTC, dr5hn requested changes
@cesariverit See my comments.

2022-02-07 12:19 UTC, cesariverit commented
That's the department (state) full name as is named in Colombia if you prefer don't change it, it's your decision. It could be understood that way.

2022-03-13 06:53 UTC, dr5hn approved these changes

2022-03-13 06:53 UTC, merged