Add City of Industry, CA, USA
dr5hn/countries-states-cities-database pull request #632
Opened 2023-07-05 17:54 UTC by scottgigante

Closes #630

2023-07-16 04:57 UTC, dr5hn requested changes
Dear @scottgigante, thank you for your efforts. Can you kindly update the name from "Industry" to "City of Industry"?

2023-08-06 17:09 UTC, dr5hn commented
@scottgigante Could you please rebase this branch and resolve conflicts, Thanks.

2023-08-08 13:27 UTC, scottgigante commented
@dr5hn done!

2023-08-11 09:36 UTC, dr5hn approved these changes

2023-08-11 09:36 UTC, merged