Fix incongruent state_code and country_code for cities in Sevastopol
dr5hn/countries-states-cities-database pull request #633
Opened 2023-07-05 17:59 UTC by scottgigante

Closes #615

2023-07-16 05:05 UTC, dr5hn requested changes
@scottgigante Thanks for working on this.

Just a heads up, you'll also need to update the state entry.

From:
```
(1912,'Sevastopol',182,'RU','20','UA-40',NULL,44.61665000,33.52536710,'2019-10-05 23:18:44','2022-08-31 15:52:51',1,'Q7525')
```

To:
```
(1912,'Sevastopol',230,'UA','20','UA-40',NULL,44.61665000,33.52536710,'2019-10-05 23:18:44','2022-08-31 15:52:51',1,'Q7525')
```

2023-08-06 17:07 UTC, dr5hn commented
@scottgigante Sorry to bother you again. `country_id` field in `states` table should also be changed to 230.

2023-08-07 16:22 UTC, scottgigante commented
Done, thanks!

2023-08-08 06:48 UTC, dr5hn approved these changes

2023-08-08 06:48 UTC, merged